### ISSUE TITLE
nu putem face remove intr-un for. Pt asta putem folosi iterator: iterator.remove()

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs10.homework.ex#1]
https://github.com/cezarhre/curs10.homework.ex/blob/f6d2782081f9d9a94754fb6a8bd4e8db6abd1691/src/ro/fasttrackit/curs10/homework/ex1/Basket.java#L24

**Comment by cezarhre** [comment]
Done

**Comment by cezarhre** [comment]
public boolean remove(String outFruit) {
        Iterator<String> iterator = fruits.iterator();
            while (iterator.hasNext()) {
                if (iterator.next().equals(outFruit)) {
                    iterator.remove();
                    return true;
                }
            }
        return false;

De ce nu elimina si al doilea element asemanator?
