### ISSUE TITLE
algoritmul tau sterge doar primul element intalnit. Si tot stergi inauntrul lui for... o sa ai probleme

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs10.homework.ex#3]
https://github.com/cezarhre/curs10.homework.ex/blob/f6d2782081f9d9a94754fb6a8bd4e8db6abd1691/src/ro/fasttrackit/curs10/homework/ex1/Basket.java#L22

**Comment by cezarhre** [comment]
Am refacut la prinz cind am vorbit...

**Comment by cezarhre** [comment]
https://github.com/cezarhre/curs10_homework/commit/a31e0605f83cf14faa6741cbca52832aab9ddb2a

**Comment by cezarhre** [comment]
Se pare ca am deschis 2 repository-uri
